### ISSUE TITLE
Citation lists not generating cite elements in xml

### ISSUE THREAD

**Issue by mdelcambre** [DCCouncil/dc-law-tools#2]
In the current xml, you can find lists of multiple citations in a row where only the first citation generated a cite element. For example:
https://github.com/DCCouncil/dc-law-xml/blob/master/dc/council/code/titles/1/sections/1001.02.xml#L51

But I did look through the add_refs, and it looks like it should catch this case, so I wasn't sure if the xml should just be regenerated.
https://github.com/DCCouncil/dc-law-tools/blob/master/build_xml/add_refs.py#L28

**Comment by dgreisen-cfpb** [comment]
Unfortunately, I was only able to get one or two cites to work. I wasn't able to get arbitrary numbers of cites to work - created a weird infinite recursion I've never seen before. It needs to be able to handle such beauties as: "cite, cite through cite, cite, cite through cite, and cite. " if you are able to make such a regex work, that would be great!

**Comment by mdelcambre** [comment]
May be able to construct something with a positive look behind. I'll see if
I can get something working.
